-- MAC ONLY SETTINGS
--
-- Put the following lines in ~/.config/ghostty/config
--
--      macos-option-as-alt = left
--      keybind = alt+left=unbind
--      keybind = alt+right=unbind
--
--      This will make the Option key work as Alt
